name: PR-checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build docker image
        run: docker build . -t $IMAGE_NAME
